language: node_js

os:
  - linux

dist: trusty

branches:
  only:
  - gh-pages
  - /.*/

node_js:
  - "14.7"
  - "12.18"
  - "10.13"
  - "8.1"
  - "7.1"
  - "6.1"
  - "5.1"
  - "4.1"

before_script:
  - npm install bindings file-uri-to-path node-addon-api
  - sudo -H apt-get install libffi-dev
  - sudo bash -c "curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash"
  - npm link ../ems
  - sudo apt-get install python-dev python3-dev
  - sudo apt-get install -y build-essential
  - sudo python2 -m pip install --upgrade pip
  - sudo python2 -m pip install cffi
  - sudo python3 -m pip install cffi

script:
  - make test

env:
  - CXX=g++-4.8

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
