language: node_js

os:
  - linux

dist: trusty

node_js:
  - "6.1"
  - "5.1"
  - "4.1"
  - "0.10"
  - "iojs"

before_script:
  - npm link ../ems
  - sudo -H apt-get install python-pip
  - sudo -H apt-get install libffi-dev
  - python3 -m pip install cffi
  - sudo -H apt-get install python3-cffi

script:
  - make test

env:
  - CXX=g++-4.8

sudo: true

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
